name: nodejs
version: 0.0.1
description: NodeJS wrapper for dart
author: GrimShield
homepage: https://gitlab.com/grimshield/nodejs.dart

environment:
  sdk: '>=1.0.0 <2.0.0'

dependencies:
  barback: '>=0.15.2 <0.16.0'
  js: '>=0.6.0 <0.7.0'

dev_dependencies:
  test: '>=0.12.0 <0.13.0'
